//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCustomerManage.Models
{
    using System;

    using System.Data.Entity;

    using System.Data.Entity.Infrastructure;



    public partial class CustomersEntities : DbContext

    {

        public CustomersEntities()

            : base("name=CustomersEntities")

        {

        }



        protected override void OnModelCreating(DbModelBuilder modelBuilder)

        {

            throw new UnintentionalCodeFirstException();

        }



        public virtual DbSet<CitiesTBL> CitiesTBLs { get; set; }

        public virtual DbSet<CustomersTBL> CustomersTBLs { get; set; }

        public virtual DbSet<SelectCities> SelectCities { get; set; }



        public System.Data.Entity.DbSet<ProjectCustomerManage.APIData.Bank> Banks { get; set; }

    }
}
