//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCustomerManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectCities
    {
        public int IDCity { get; set; }
        public string NameCity { get; set; }
    }
}
